/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.memoryMatchingGame.ui;

import com.memoryMatchingGame.lib.WordLibrary;
import com.memoryMatchingGame.ui.GridPanel;
import javax.swing.Timer;

/**
 *
 */
public class Main extends javax.swing.JFrame {

    private enum Difficulty {

        Easy, Moderate, Difficult
    }
    // static members
    final private int Grid4x4 = 4;
    final private int Grid6x6 = 6;
    final private int Grid8x8 = 8;

    // member variables
    private Difficulty difficulty;

    // Main form construtor

    public Main() {
        initGame();
        initComponents();
    }

    // Game elements init
    private void initGame() {
        difficulty = Difficulty.Easy;
        newGame(difficulty);
    }

    private void newGame(Difficulty _currentDiff) {
        switch(_currentDiff) {
            case Easy:
                
                break;
            case Moderate:
                
                 break;
            case Difficult:
                
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNewGame = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioDiff1 = new javax.swing.JRadioButtonMenuItem();
        jRadioDiff2 = new javax.swing.JRadioButtonMenuItem();
        jRadioDiff3 = new javax.swing.JRadioButtonMenuItem();
        jMenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Game");

        jMenuNewGame.setText("New Game");
        jMenuNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewGameActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNewGame);

        jMenu2.setText("Mode");

        jRadioDiff1.setSelected(true);
        jRadioDiff1.setText("4 x 4 grid (Easy)");
        jRadioDiff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDiff1ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioDiff1);

        jRadioDiff2.setText("6 x 6 grid (Moderate)");
        jRadioDiff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDiff2ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioDiff2);

        jRadioDiff3.setText("8 X 8 grid (Difficult)");
        jRadioDiff3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDiff3ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioDiff3);

        jMenu1.add(jMenu2);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jRadioDiff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDiff1ActionPerformed
        // TODO add your handling code here:
        difficulty = Difficulty.Easy;
        this.jRadioDiff1.setSelected(true);
        this.jRadioDiff2.setSelected(false);
        this.jRadioDiff3.setSelected(false);
    }//GEN-LAST:event_jRadioDiff1ActionPerformed

    private void jRadioDiff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDiff2ActionPerformed
        // TODO add your handling code here:
        difficulty = Difficulty.Moderate;
        this.jRadioDiff1.setSelected(false);
        this.jRadioDiff2.setSelected(true);
        this.jRadioDiff3.setSelected(false);
    }//GEN-LAST:event_jRadioDiff2ActionPerformed

    private void jRadioDiff3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDiff3ActionPerformed
        // TODO add your handling code here:
        difficulty = Difficulty.Difficult;
        this.jRadioDiff1.setSelected(false);
        this.jRadioDiff2.setSelected(false);
        this.jRadioDiff3.setSelected(true);
    }//GEN-LAST:event_jRadioDiff3ActionPerformed

    private void jMenuNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewGameActionPerformed
        // TODO add your handling code here:
        newGame(difficulty);
    }//GEN-LAST:event_jMenuNewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuNewGame;
    private javax.swing.JRadioButtonMenuItem jRadioDiff1;
    private javax.swing.JRadioButtonMenuItem jRadioDiff2;
    private javax.swing.JRadioButtonMenuItem jRadioDiff3;
    // End of variables declaration//GEN-END:variables
}
