/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.memoryMatchingGame.ui;
import java.awt.*;

/**
 *
 */
public class Main extends javax.swing.JFrame {

    private enum Difficulty {

        Easy, Moderate, Difficult
    }
    // static members
    final private int Grid4x4 = 4;
    final private int Grid6x6 = 6;
    final private int Grid8x8 = 8;

    // member variables
    private Difficulty difficulty;
    private int paringInterval;
    private final GridPanel grid = new GridPanel();

    // Main form construtor
    public Main() {
        initGame();
        initComponents();
        setTitle("Final Project - Periodic Table Memory Matching Game");
        this.setSize(new Dimension(400,65));
        
    }

    // Game elements init
    private void initGame() {
        this.add(grid, BorderLayout.WEST);
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 3, Toolkit.getDefaultToolkit().getScreenSize().height / 3);
        difficulty = Difficulty.Easy;
        paringInterval = 5;
    }

    private void newGame(Difficulty _currentDiff) {

        switch (_currentDiff) {
            case Easy:
                grid.Init(Grid4x4, paringInterval);
                break;
            case Moderate:
                grid.Init(Grid6x6, paringInterval);
                break;
            case Difficult:
                grid.Init(Grid8x8, paringInterval);
                break;
        }
        this.pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNewGame = new javax.swing.JMenuItem();
        jMenuLevels = new javax.swing.JMenu();
        jRadioDiff1 = new javax.swing.JRadioButtonMenuItem();
        jRadioDiff2 = new javax.swing.JRadioButtonMenuItem();
        jRadioDiff3 = new javax.swing.JRadioButtonMenuItem();
        jMenuTime = new javax.swing.JMenu();
        jRadioButtonMenuFiveSeconds = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuThreeSeconds = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuOneSeconds = new javax.swing.JRadioButtonMenuItem();
        jMenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Game");

        jMenuNewGame.setText("New Game");
        jMenuNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewGameActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNewGame);

        jMenuLevels.setText("Levels");

        jRadioDiff1.setSelected(true);
        jRadioDiff1.setText("4 x 4 grid");
        jRadioDiff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDiff1ActionPerformed(evt);
            }
        });
        jMenuLevels.add(jRadioDiff1);

        jRadioDiff2.setText("6 x 6 grid");
        jRadioDiff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDiff2ActionPerformed(evt);
            }
        });
        jMenuLevels.add(jRadioDiff2);

        jRadioDiff3.setText("8 X 8 grid");
        jRadioDiff3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDiff3ActionPerformed(evt);
            }
        });
        jMenuLevels.add(jRadioDiff3);

        jMenu1.add(jMenuLevels);

        jMenuTime.setText("Time");

        jRadioButtonMenuFiveSeconds.setSelected(true);
        jRadioButtonMenuFiveSeconds.setText("5 Seconds");
        jRadioButtonMenuFiveSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuFiveSecondsActionPerformed(evt);
            }
        });
        jMenuTime.add(jRadioButtonMenuFiveSeconds);

        jRadioButtonMenuThreeSeconds.setText("3 Seconds");
        jRadioButtonMenuThreeSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuThreeSecondsActionPerformed(evt);
            }
        });
        jMenuTime.add(jRadioButtonMenuThreeSeconds);

        jRadioButtonMenuOneSeconds.setText("1 Seconds");
        jRadioButtonMenuOneSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuOneSecondsActionPerformed(evt);
            }
        });
        jMenuTime.add(jRadioButtonMenuOneSeconds);

        jMenu1.add(jMenuTime);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jRadioDiff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDiff1ActionPerformed
        // TODO add your handling code here:
        difficulty = Difficulty.Easy;
        this.jRadioDiff1.setSelected(true);
        this.jRadioDiff2.setSelected(false);
        this.jRadioDiff3.setSelected(false);
    }//GEN-LAST:event_jRadioDiff1ActionPerformed

    private void jRadioDiff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDiff2ActionPerformed
        // TODO add your handling code here:
        difficulty = Difficulty.Moderate;
        this.jRadioDiff1.setSelected(false);
        this.jRadioDiff2.setSelected(true);
        this.jRadioDiff3.setSelected(false);
    }//GEN-LAST:event_jRadioDiff2ActionPerformed

    private void jRadioDiff3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDiff3ActionPerformed
        // TODO add your handling code here:
        difficulty = Difficulty.Difficult;
        this.jRadioDiff1.setSelected(false);
        this.jRadioDiff2.setSelected(false);
        this.jRadioDiff3.setSelected(true);
    }//GEN-LAST:event_jRadioDiff3ActionPerformed

    private void jMenuNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewGameActionPerformed
        // TODO add your handling code here:
        this.newGame(difficulty);
    }//GEN-LAST:event_jMenuNewGameActionPerformed

    private void jRadioButtonMenuFiveSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuFiveSecondsActionPerformed
        // TODO add your handling code here:
        paringInterval = 5;
        this.jRadioButtonMenuFiveSeconds.setSelected(true);
        this.jRadioButtonMenuThreeSeconds.setSelected(false);
        this.jRadioButtonMenuOneSeconds.setSelected(false);
    }//GEN-LAST:event_jRadioButtonMenuFiveSecondsActionPerformed

    private void jRadioButtonMenuThreeSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuThreeSecondsActionPerformed
        // TODO add your handling code here:
        paringInterval = 3;
        this.jRadioButtonMenuFiveSeconds.setSelected(false);
        this.jRadioButtonMenuThreeSeconds.setSelected(true);
        this.jRadioButtonMenuOneSeconds.setSelected(false);
    }//GEN-LAST:event_jRadioButtonMenuThreeSecondsActionPerformed

    private void jRadioButtonMenuOneSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuOneSecondsActionPerformed
        // TODO add your handling code here:
        paringInterval = 1;
        this.jRadioButtonMenuFiveSeconds.setSelected(false);
        this.jRadioButtonMenuThreeSeconds.setSelected(false);
        this.jRadioButtonMenuOneSeconds.setSelected(true);
    }//GEN-LAST:event_jRadioButtonMenuOneSecondsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuLevels;
    private javax.swing.JMenuItem jMenuNewGame;
    private javax.swing.JMenu jMenuTime;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuFiveSeconds;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuOneSeconds;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuThreeSeconds;
    private javax.swing.JRadioButtonMenuItem jRadioDiff1;
    private javax.swing.JRadioButtonMenuItem jRadioDiff2;
    private javax.swing.JRadioButtonMenuItem jRadioDiff3;
    // End of variables declaration//GEN-END:variables
}
